//! Build script for medcodes crate - generates ICD-10-CM and CCSR data

#![allow(clippy::expect_used)]
#![allow(clippy::panic)]
#![allow(clippy::type_complexity)]
#![allow(clippy::unwrap_or_default)]

use quick_xml::Reader;
use quick_xml::events::Event;
use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;

fn main() {
    // Only check for data changes if data directory exists
    // This allows publishing to crates.io without including large data files
    let data_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/data");
    if Path::new(data_dir).exists() {
        println!("cargo:rerun-if-changed=data/april-1-2026-code-tables-tabular-and-index.zip");
        println!("cargo:rerun-if-changed=data/DXCCSR-v2026-1.zip");
    }

    // Generate ICD-10-CM data
    let icd10_data_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/data/Table and Index/icd10cm_tabular_2026.xml"
    );

    if Path::new(icd10_data_path).exists() {
        eprintln!("Found CMS data file at {icd10_data_path}");
        match parse_cms_xml(icd10_data_path) {
            Ok((codes, parents, children)) => {
                eprintln!("Successfully parsed CMS data, generating maps...");
                generate_phf_maps(&codes, &parents, &children);
            }
            Err(e) => {
                eprintln!("Warning: Failed to parse CMS XML: {e}");
                eprintln!("Using empty maps. Ensure the CMS data is extracted properly.");
                generate_empty_maps();
            }
        }
    } else {
        eprintln!("Warning: CMS data file not found at {icd10_data_path}");
        eprintln!("Extract the ZIP file to populate ICD-10-CM codes, or use with-data feature.");
        generate_empty_maps();
    }

    // Generate CCSR mapping data
    let ccsr_csv_path = concat!(env!("CARGO_MANIFEST_DIR"), "/data/DXCCSR_v2026-1.csv");

    if Path::new(ccsr_csv_path).exists() {
        eprintln!("Found CCSR data file at {ccsr_csv_path}");
        match parse_ccsr_csv(ccsr_csv_path) {
            Ok(mappings) => {
                eprintln!("Successfully parsed CCSR data, generating mappings...");
                generate_ccsr_maps(&mappings);
            }
            Err(e) => {
                eprintln!("Warning: Failed to parse CCSR CSV: {e}");
                eprintln!("Using empty CCSR mappings.");
                generate_empty_ccsr_maps();
            }
        }
    } else {
        eprintln!("Warning: CCSR data file not found at {ccsr_csv_path}");
        eprintln!("Extract the ZIP file to populate CCSR mappings, or use with-data feature.");
        generate_empty_ccsr_maps();
    }
}

fn generate_empty_maps() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("icd10cm_data.rs");

    let empty_code = r"
// Generated by build.rs - empty maps
/// ICD-10-CM code descriptions (empty - data not loaded)
pub static ICD10_CM_DESCRIPTIONS: phf::Map<&'static str, &'static str> = phf_map! {};
/// ICD-10-CM parent code mapping (empty - data not loaded)
pub static ICD10_CM_PARENTS: phf::Map<&'static str, Option<&'static str>> = phf_map! {};
/// ICD-10-CM child code mapping (empty - data not loaded)
pub static ICD10_CM_CHILDREN: phf::Map<&'static str, &'static [&'static str]> = phf_map! {};
";

    if let Err(e) = std::fs::write(&out_path, empty_code) {
        panic!("Failed to write empty maps: {e}");
    }
    eprintln!("Generated empty ICD-10-CM maps at {}", out_path.display());
}

fn parse_cms_xml(
    path: &str,
) -> Result<
    (
        Vec<(String, String)>,
        Vec<(String, String)>,
        HashMap<String, Vec<String>>,
    ),
    Box<dyn std::error::Error>,
> {
    let mut reader = Reader::from_file(path)?;
    let mut buf = Vec::new();
    let mut codes = Vec::new();
    let mut parents = Vec::new();
    let mut children: HashMap<String, Vec<String>> = HashMap::new();

    let mut current_code: Option<String> = None;
    let mut current_desc: Option<String> = None;
    let mut in_name = false;
    let mut in_desc = false;

    loop {
        match reader.read_event_into(&mut buf)? {
            Event::Start(e) => match e.name().as_ref() {
                b"name" => in_name = true,
                b"desc" => in_desc = true,
                _ => {}
            },
            Event::Text(e) => {
                let text = e.unescape()?.to_string();
                if in_name {
                    current_code = Some(text.to_uppercase());
                } else if in_desc {
                    current_desc = Some(text);
                }
            }
            Event::End(e) => {
                match e.name().as_ref() {
                    b"name" => in_name = false,
                    b"desc" => in_desc = false,
                    b"diag" | b"procedure" => {
                        // End of a code entry
                        if let (Some(code), Some(desc)) = (current_code.take(), current_desc.take())
                            && !code.is_empty()
                            && !desc.is_empty()
                        {
                            // Extract parent code by removing the last character after removing dots
                            // This handles codes like "I10.9" -> "I10" and "A01.0" -> "A01"
                            let normalized = code.replace('.', "");
                            if normalized.len() > 3 {
                                let parent_normalized =
                                    normalized[..normalized.len() - 1].to_string();
                                parents.push((code.clone(), parent_normalized.clone()));
                                children
                                    .entry(parent_normalized)
                                    .or_insert_with(Vec::new)
                                    .push(code.clone());
                            } else {
                                // Top-level codes have no parent
                                parents.push((code.clone(), String::new()));
                            }
                            codes.push((code, desc));
                        }
                    }
                    _ => {}
                }
            }
            Event::Eof => break,
            _ => {}
        }
        buf.clear();
    }

    Ok((codes, parents, children))
}

fn generate_phf_maps(
    codes: &[(String, String)],
    parents: &[(String, String)],
    children: &HashMap<String, Vec<String>>,
) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("icd10cm_data.rs");

    eprintln!("Parsed {} ICD-10-CM codes", codes.len());
    eprintln!("Found {} parent-child relationships", children.len());

    // Generate Rust code
    let mut output = String::new();
    output.push_str("// Generated by build.rs from CMS ICD-10-CM data\n\n");

    // Generate descriptions map - store descriptions and create Code structs on demand
    output.push_str("/// ICD-10-CM code descriptions.\n");
    output.push_str("/// Generated from CMS April 1, 2026 code tables.\n");
    output.push_str(
        "pub static ICD10_CM_DESCRIPTIONS: phf::Map<&'static str, &'static str> = phf_map! {\n",
    );
    for (code, desc) in codes {
        let escaped_desc = desc
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t");
        let _ = writeln!(output, "    \"{code}\" => \"{escaped_desc}\",");
    }
    output.push_str("};\n\n");

    // Generate parents map
    output.push_str("/// ICD-10-CM parent code mapping for hierarchy traversal.\n");
    output.push_str("/// Maps normalized codes to their immediate parent codes.\n");
    output.push_str(
        "pub static ICD10_CM_PARENTS: phf::Map<&'static str, Option<&'static str>> = phf_map! {\n",
    );
    for (code, parent) in parents {
        if parent.is_empty() {
            let _ = writeln!(output, "    \"{code}\" => None,");
        } else {
            let _ = writeln!(output, "    \"{code}\" => Some(\"{parent}\"),");
        }
    }
    output.push_str("};\n\n");

    // Generate children map
    output.push_str("/// ICD-10-CM child code mapping for hierarchy traversal.\n");
    output.push_str("/// Maps normalized codes to their immediate child codes.\n");
    output.push_str("pub static ICD10_CM_CHILDREN: phf::Map<&'static str, &'static [&'static str]> = phf_map! {\n");
    for (parent, child_list) in children {
        // Sort and deduplicate child list for deterministic builds
        let mut sorted_children = child_list.clone();
        sorted_children.sort();
        sorted_children.dedup();

        let children_str = sorted_children
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(output, "    \"{parent}\" => &[{children_str}],");
    }
    output.push_str("};\n");

    if let Err(e) = std::fs::write(&out_path, output) {
        panic!("Failed to write ICD-10-CM data: {e}");
    }
    eprintln!("Generated ICD-10-CM data at {}", out_path.display());
}

// CCSR data structures and parsing

#[derive(Debug, Clone)]
struct CcsrCodeMapping {
    icd10_code: String,
    categories: Vec<ParsedCcsrCategory>,
}

#[derive(Debug, Clone)]
struct ParsedCcsrCategory {
    code: String,
    description: String,
    is_default_ip: bool,
    is_default_ed: bool,
    is_default_op: bool,
}

fn parse_ccsr_csv(path: &str) -> Result<Vec<CcsrCodeMapping>, Box<dyn std::error::Error>> {
    let mut reader = csv::Reader::from_path(path)?;
    let mut mappings: HashMap<String, CcsrCodeMapping> = HashMap::new();

    for result in reader.records() {
        let record = result?;

        // Parse ICD-10-CM code (column 0)
        let icd10_code = record
            .get(0)
            .ok_or("Missing ICD-10-CM code")?
            .trim()
            .to_uppercase();

        if icd10_code.is_empty() {
            continue;
        }

        // Parse default categories for different contexts
        let default_inpatient = record.get(2).unwrap_or("").trim();
        let default_ed = record.get(4).unwrap_or("").trim();
        let default_outpatient = record.get(6).unwrap_or("").trim();

        // Parse all CCSR categories (up to 6)
        let mut categories = Vec::new();
        for i in 0..6 {
            let cat_col = 8 + i * 2; // Categories start at column 8
            let desc_col = cat_col + 1;

            if let Some(cat_code) = record.get(cat_col) {
                let cat_code = cat_code.trim();
                if !cat_code.is_empty() && cat_code != "' '" {
                    let description = record.get(desc_col).unwrap_or("").trim().to_string();

                    let is_default_inpatient = default_inpatient == cat_code;
                    let is_default_ed = default_ed == cat_code;
                    let is_default_outpatient = default_outpatient == cat_code;

                    categories.push(ParsedCcsrCategory {
                        code: cat_code.replace('\'', ""),
                        description,
                        is_default_ip: is_default_inpatient,
                        is_default_ed,
                        is_default_op: is_default_outpatient,
                    });
                }
            }
        }

        if !categories.is_empty() {
            let _ = mappings.insert(
                icd10_code.clone(),
                CcsrCodeMapping {
                    icd10_code,
                    categories,
                },
            );
        }
    }

    let result: Vec<CcsrCodeMapping> = mappings.into_values().collect();
    eprintln!("Parsed {} ICD-10-CM to CCSR mappings", result.len());
    Ok(result)
}

fn generate_empty_ccsr_maps() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("ccsr_data.rs");

    let empty_code = r"
// Generated by build.rs - empty CCSR maps
use phf::phf_map;

/// ICD-10-CM to CCSR mappings (empty - data not loaded)
pub static ICD10CM_TO_CCSR_MAPPINGS: phf::Map<&'static str, &'static [CcsrMapping]> = phf_map! {};
/// CCSR to ICD-10-CM reverse mappings (empty - data not loaded)
pub static CCSR_TO_ICD10CM_MAPPINGS: phf::Map<&'static str, &'static [&'static str]> = phf_map! {};
";

    if let Err(e) = std::fs::write(&out_path, empty_code) {
        panic!("Failed to write empty CCSR maps: {e}");
    }
    eprintln!("Generated empty CCSR maps at {}", out_path.display());
}

fn generate_ccsr_maps(mappings: &[CcsrCodeMapping]) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("ccsr_data.rs");

    let mut output = String::new();
    output.push_str("// Generated by build.rs from AHRQ CCSR data\n\n");
    output.push_str("use phf::phf_map;\n\n");

    // Generate all CCSR mappings as a single large static array
    output.push_str("static CCSR_MAPPINGS: &[crate::ccsr::CcsrMapping] = &[\n");

    for mapping in mappings {
        for cat in &mapping.categories {
            let _ = writeln!(
                output,
                "    crate::ccsr::CcsrMapping {{\n        category_code: \"{}\",\n        category_description: \"{}\",\n        is_default_ip: {},\n        is_default_ed: {},\n        is_default_op: {},\n    }},",
                cat.code.replace('"', "\\\""),
                cat.description.replace('"', "\\\""),
                cat.is_default_ip,
                cat.is_default_ed,
                cat.is_default_op
            );
        }
    }

    output.push_str("];\n\n");

    // Generate index map for ICD-10-CM -> CCSR
    output.push_str("/// ICD-10-CM to CCSR mappings\n");
    output.push_str("/// Maps normalized ICD-10-CM codes to indices in `CCSR_MAPPINGS` array\n");
    output.push_str("pub static ICD10CM_TO_CCSR_MAPPINGS: phf::Map<&'static str, &'static [usize]> = phf_map! {\n");

    let mut current_index = 0;
    for mapping in mappings {
        let count = mapping.categories.len();
        if count > 0 {
            let indices: Vec<String> = (current_index..current_index + count)
                .map(|i| i.to_string())
                .collect();
            let _ = writeln!(
                output,
                "    \"{}\" => &[{}],",
                mapping.icd10_code,
                indices.join(", ")
            );
            current_index += count;
        }
    }

    output.push_str("};\n\n");

    // Generate reverse mapping (CCSR -> ICD-10-CM)
    let mut reverse_mappings: HashMap<String, Vec<String>> = HashMap::new();
    for mapping in mappings {
        for cat in &mapping.categories {
            reverse_mappings
                .entry(cat.code.clone())
                .or_insert_with(Vec::new)
                .push(mapping.icd10_code.clone());
        }
    }

    // Sort and deduplicate ICD-10-CM codes for each CCSR category
    for icd10_codes in reverse_mappings.values_mut() {
        icd10_codes.sort();
        icd10_codes.dedup();
    }

    output.push_str("/// CCSR to ICD-10-CM reverse mappings\n");
    output.push_str("/// Maps CCSR categories to their ICD-10-CM codes\n");
    output.push_str("pub static CCSR_TO_ICD10CM_MAPPINGS: phf::Map<&'static str, &'static [&'static str]> = phf_map! {\n");

    for (ccsr_code, icd10_codes) in &reverse_mappings {
        let icd10_str = icd10_codes
            .iter()
            .map(|code| format!("\"{code}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(output, "    \"{ccsr_code}\" => &[{icd10_str}],");
    }

    output.push_str("};\n");

    if let Err(e) = std::fs::write(&out_path, output) {
        panic!("Failed to write CCSR data: {e}");
    }
    eprintln!(
        "Generated CCSR data at {} with {} mappings",
        out_path.display(),
        mappings.len()
    );
}
