//! Build script for medcodes crate - generates ICD-10-CM data from CMS XML files

#![allow(clippy::expect_used)]
#![allow(clippy::panic)]
#![allow(clippy::type_complexity)]
#![allow(clippy::unwrap_or_default)]

use quick_xml::Reader;
use quick_xml::events::Event;
use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/april-1-2026-code-tables-tabular-and-index.zip");

    let data_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/data/Table and Index/icd10cm_tabular_2026.xml"
    );

    if Path::new(data_path).exists() {
        eprintln!("Found CMS data file at {data_path}");
        match parse_cms_xml(data_path) {
            Ok((codes, parents, children)) => {
                eprintln!("Successfully parsed CMS data, generating maps...");
                generate_phf_maps(&codes, &parents, &children);
            }
            Err(e) => {
                eprintln!("Warning: Failed to parse CMS XML: {e}");
                eprintln!("Using empty maps. Ensure the CMS data is extracted properly.");
                generate_empty_maps();
            }
        }
    } else {
        eprintln!("Warning: CMS data file not found at {data_path}");
        eprintln!("Extract the ZIP file to populate ICD-10-CM codes.");
        generate_empty_maps();
    }
}

fn generate_empty_maps() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("icd10cm_data.rs");

    let empty_code = r"
// Generated by build.rs - empty maps
/// ICD-10-CM code descriptions (empty - data not loaded)
pub static ICD10_CM_DESCRIPTIONS: phf::Map<&'static str, &'static str> = phf_map! {};
/// ICD-10-CM parent code mapping (empty - data not loaded)
pub static ICD10_CM_PARENTS: phf::Map<&'static str, Option<&'static str>> = phf_map! {};
/// ICD-10-CM child code mapping (empty - data not loaded)
pub static ICD10_CM_CHILDREN: phf::Map<&'static str, &'static [&'static str]> = phf_map! {};
";

    if let Err(e) = std::fs::write(&out_path, empty_code) {
        panic!("Failed to write empty maps: {e}");
    }
    eprintln!("Generated empty ICD-10-CM maps at {}", out_path.display());
}

fn parse_cms_xml(
    path: &str,
) -> Result<
    (
        Vec<(String, String)>,
        Vec<(String, String)>,
        HashMap<String, Vec<String>>,
    ),
    Box<dyn std::error::Error>,
> {
    let mut reader = Reader::from_file(path)?;
    let mut buf = Vec::new();
    let mut codes = Vec::new();
    let mut parents = Vec::new();
    let mut children: HashMap<String, Vec<String>> = HashMap::new();

    let mut current_code: Option<String> = None;
    let mut current_desc: Option<String> = None;
    let mut in_name = false;
    let mut in_desc = false;

    loop {
        match reader.read_event_into(&mut buf)? {
            Event::Start(e) => match e.name().as_ref() {
                b"name" => in_name = true,
                b"desc" => in_desc = true,
                _ => {}
            },
            Event::Text(e) => {
                let text = e.unescape()?.to_string();
                if in_name {
                    current_code = Some(text.to_uppercase());
                } else if in_desc {
                    current_desc = Some(text);
                }
            }
            Event::End(e) => {
                match e.name().as_ref() {
                    b"name" => in_name = false,
                    b"desc" => in_desc = false,
                    b"diag" | b"procedure" => {
                        // End of a code entry
                        if let (Some(code), Some(desc)) = (current_code.take(), current_desc.take())
                            && !code.is_empty()
                            && !desc.is_empty()
                        {
                            // Extract parent code by removing the last character after removing dots
                            // This handles codes like "I10.9" -> "I10" and "A01.0" -> "A01"
                            let normalized = code.replace('.', "");
                            if normalized.len() > 3 {
                                let parent_normalized =
                                    normalized[..normalized.len() - 1].to_string();
                                parents.push((code.clone(), parent_normalized.clone()));
                                children
                                    .entry(parent_normalized)
                                    .or_insert_with(Vec::new)
                                    .push(code.clone());
                            } else {
                                // Top-level codes have no parent
                                parents.push((code.clone(), String::new()));
                            }
                            codes.push((code, desc));
                        }
                    }
                    _ => {}
                }
            }
            Event::Eof => break,
            _ => {}
        }
        buf.clear();
    }

    Ok((codes, parents, children))
}

fn generate_phf_maps(
    codes: &[(String, String)],
    parents: &[(String, String)],
    children: &HashMap<String, Vec<String>>,
) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let out_path = std::path::Path::new(&out_dir).join("icd10cm_data.rs");

    eprintln!("Parsed {} ICD-10-CM codes", codes.len());
    eprintln!("Found {} parent-child relationships", children.len());

    // Generate Rust code
    let mut output = String::new();
    output.push_str("// Generated by build.rs from CMS ICD-10-CM data\n\n");

    // Generate descriptions map - store descriptions and create Code structs on demand
    output.push_str("/// ICD-10-CM code descriptions.\n");
    output.push_str("/// Generated from CMS April 1, 2026 code tables.\n");
    output.push_str(
        "pub static ICD10_CM_DESCRIPTIONS: phf::Map<&'static str, &'static str> = phf_map! {\n",
    );
    for (code, desc) in codes {
        let escaped_desc = desc
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t");
        let _ = writeln!(output, "    \"{code}\" => \"{escaped_desc}\",");
    }
    output.push_str("};\n\n");

    // Generate parents map
    output.push_str("/// ICD-10-CM parent code mapping for hierarchy traversal.\n");
    output.push_str("/// Maps normalized codes to their immediate parent codes.\n");
    output.push_str(
        "pub static ICD10_CM_PARENTS: phf::Map<&'static str, Option<&'static str>> = phf_map! {\n",
    );
    for (code, parent) in parents {
        if parent.is_empty() {
            let _ = writeln!(output, "    \"{code}\" => None,");
        } else {
            let _ = writeln!(output, "    \"{code}\" => Some(\"{parent}\"),");
        }
    }
    output.push_str("};\n\n");

    // Generate children map
    output.push_str("/// ICD-10-CM child code mapping for hierarchy traversal.\n");
    output.push_str("/// Maps normalized codes to their immediate child codes.\n");
    output.push_str("pub static ICD10_CM_CHILDREN: phf::Map<&'static str, &'static [&'static str]> = phf_map! {\n");
    for (parent, child_list) in children {
        // Sort and deduplicate child list for deterministic builds
        let mut sorted_children = child_list.clone();
        sorted_children.sort();
        sorted_children.dedup();

        let children_str = sorted_children
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(output, "    \"{parent}\" => &[{children_str}],");
    }
    output.push_str("};\n");

    if let Err(e) = std::fs::write(&out_path, output) {
        panic!("Failed to write ICD-10-CM data: {e}");
    }
    eprintln!("Generated ICD-10-CM data at {}", out_path.display());
}
