//! ICD-10-CM (International Classification of Diseases, 10th Revision, Clinical Modification)
//!
//! This module provides ICD-10-CM code lookup, validation, and hierarchy traversal.

use crate::{Code, CodeSystem, Error, System};
use phf::phf_map;

/// ICD-10-CM code system implementation.
#[derive(Debug)]
pub struct Icd10Cm {
    /// Map of normalized codes to Code information
    codes: &'static phf::Map<&'static str, Code>,
    /// Map of codes to their parent codes
    parents: &'static phf::Map<&'static str, Option<&'static str>>,
    /// Map of codes to their children codes
    children: &'static phf::Map<&'static str, &'static [&'static str]>,
}

impl Icd10Cm {
    /// Create a new ICD-10-CM code system instance.
    pub fn new() -> Self {
        Self {
            codes: &ICD10_CM_CODES,
            parents: &ICD10_CM_PARENTS,
            children: &ICD10_CM_CHILDREN,
        }
    }

    /// Normalize an ICD-10-CM code (remove dots, uppercase).
    ///
    /// # Examples
    ///
    /// ```
    /// use medcodes::icd10::Icd10Cm;
    ///
    /// let icd10 = Icd10Cm::new();
    /// assert_eq!(icd10.normalize("I10.9"), "I109");
    /// assert_eq!(icd10.normalize("i10.9"), "I109");
    /// ```
    pub fn normalize(&self, code: &str) -> String {
        code.replace('.', "").to_uppercase()
    }
}

impl Default for Icd10Cm {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeSystem for Icd10Cm {
    /// Look up an ICD-10-CM code.
    fn lookup(&self, code: &str) -> Result<Code, Error> {
        let normalized = self.normalize(code);
        self.codes
            .get(&normalized)
            .cloned()
            .ok_or_else(|| Error::not_found(code, System::Icd10Cm))
    }

    /// Check if a code is valid in ICD-10-CM.
    fn is_valid(&self, code: &str) -> bool {
        let normalized = self.normalize(code);
        self.codes.contains_key(&normalized)
    }

    /// Normalize an ICD-10-CM code.
    fn normalize(&self, code: &str) -> String {
        self.normalize(code)
    }

    /// Get all ancestors of a code in the ICD-10-CM hierarchy.
    fn ancestors(&self, code: &str) -> Result<Vec<Code>, Error> {
        let normalized = self.normalize(code);
        let mut ancestors = Vec::new();
        let mut current = normalized;

        while let Some(Some(parent)) = self.parents.get(&current) {
            if let Some(parent_code) = self.codes.get(parent) {
                ancestors.push(parent_code.clone());
                current = parent.to_string();
            } else {
                break;
            }
        }

        Ok(ancestors)
    }

    /// Get all descendants of a code in the ICD-10-CM hierarchy.
    fn descendants(&self, code: &str) -> Result<Vec<Code>, Error> {
        let normalized = self.normalize(code);
        let mut descendants = Vec::new();
        let mut to_visit = vec![normalized];

        while let Some(current) = to_visit.pop() {
            if let Some(children) = self.children.get(&current) {
                for child in *children {
                    if let Some(child_code) = self.codes.get(child) {
                        descendants.push(child_code.clone());
                        to_visit.push(child.to_string());
                    }
                }
            }
        }

        Ok(descendants)
    }

    /// Get the immediate parent of a code.
    fn parent(&self, code: &str) -> Result<Option<Code>, Error> {
        let normalized = self.normalize(code);
        if let Some(Some(parent)) = self.parents.get(&normalized) {
            if let Some(parent_code) = self.codes.get(parent) {
                Ok(Some(parent_code.clone()))
            } else {
                Ok(None)
            }
        } else {
            Ok(None)
        }
    }

    /// Get all immediate children of a code.
    fn children(&self, code: &str) -> Result<Vec<Code>, Error> {
        let normalized = self.normalize(code);
        if let Some(children) = self.children.get(&normalized) {
            let mut result = Vec::new();
            for child in *children {
                if let Some(child_code) = self.codes.get(child) {
                    result.push(child_code.clone());
                }
            }
            Ok(result)
        } else {
            Ok(Vec::new())
        }
    }
}

// Static data will be generated by build.rs
static ICD10_CM_CODES: phf::Map<&'static str, Code> = phf_map! {};
static ICD10_CM_PARENTS: phf::Map<&'static str, Option<&'static str>> = phf_map! {};
static ICD10_CM_CHILDREN: phf::Map<&'static str, &'static [&'static str]> = phf_map! {};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_normalize() {
        let icd10 = Icd10Cm::new();
        assert_eq!(icd10.normalize("I10.9"), "I109");
        assert_eq!(icd10.normalize("i10.9"), "I109");
        assert_eq!(icd10.normalize("A01"), "A01");
    }

    #[test]
    fn test_is_valid() {
        let icd10 = Icd10Cm::new();
        // These will be false until we populate the data
        assert!(!icd10.is_valid("I10.9"));
        assert!(!icd10.is_valid("INVALID"));
    }
}
